package person.kinman.cogame.ai;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import person.kinman.cogame.core.action.GameAction;
import person.kinman.cogame.core.model.Direction;
import person.kinman.cogame.core.model.GameState;
import person.kinman.cogame.core.rule.GameEngine;

public class AiTest {

    @Test
    public void testAiComputesValidTurn() {
        GameState state = new GameState();
        HeuristicAi ai = new HeuristicAi(2);

        // Turn 1: P1
        // P1 moves and locks
        GameEngine.executeAction(state, 1, GameAction.lock());
        Assertions.assertEquals(2, state.getCurrentTurn());

        // Turn 2: P2 (AI)
        AiDecision decision = ai.computeTurn(state, 2);
        Assertions.assertNotNull(decision);
        Assertions.assertFalse(decision.getActions().isEmpty());

        // Execute all actions generated by AI
        for (GameAction action : decision.getActions()) {
            boolean ok = GameEngine.executeAction(state, 2, action);
            Assertions.assertTrue(ok, "Action execution failed: " + action.getType());
        }

        // After AI locks, turn should either switch back to P1 or game is over
        Assertions.assertTrue(state.getCurrentTurn() == 1 || state.isOver());
    }

    @Test
    public void testAiOn13x13Board() {
        GameState state = new GameState(13);
        HeuristicAi ai = new HeuristicAi(2);

        // P1 moves and locks on 13x13
        GameEngine.executeAction(state, 1, GameAction.lock());
        Assertions.assertEquals(2, state.getCurrentTurn());

        // AI computes move from (12, 12)
        AiDecision decision = ai.computeTurn(state, 2);
        Assertions.assertNotNull(decision);
        Assertions.assertFalse(decision.getActions().isEmpty());

        for (GameAction action : decision.getActions()) {
            boolean ok = GameEngine.executeAction(state, 2, action);
            Assertions.assertTrue(ok);
        }
        Assertions.assertTrue(state.getCurrentTurn() == 1 || state.isOver());
    }

    @Test
    public void testAiChoosesWinningCut() {
        GameState state = new GameState();
        // P1 在 (0,0)，其右侧边已被封锁
        state.getBoard().lockEdge(0, 0, Direction.RIGHT, 1);
        // AI 位于 (1,0)，朝向 UP。此时若封锁 UP，P1 将被彻底封死在 (0,0)，AI 独占 35 格必胜！
        state.getP2().setR(1);
        state.getP2().setC(0);
        state.getP2().setDirection(Direction.UP);
        state.setCurrentTurn(2);

        HeuristicAi ai = new HeuristicAi(1);
        AiDecision decision = ai.computeTurn(state, 2);
        Assertions.assertNotNull(decision);

        for (GameAction act : decision.getActions()) {
            GameEngine.executeAction(state, 2, act);
        }
        Assertions.assertTrue(state.isOver(), "AI 应当识别并执行必胜封锁");
        Assertions.assertEquals(2, state.getWinner(), "AI 应当获得胜利");
        Assertions.assertEquals(35, state.getP2Territory());
        Assertions.assertEquals(1, state.getP1Territory());
    }

    @Test
    public void testCeTianStrategyDeepSearch() {
        GameState state = new GameState(6);
        GameEngine.executeAction(state, 1, GameAction.lock());

        // 测试深度 5 (默认) 与深度 10 (最大)
        CeTianStrategy ct5 = new CeTianStrategy(5);
        Assertions.assertEquals(5, ct5.getSearchDepth());
        AiDecision dec5 = ct5.computeTurn(state, 2);
        Assertions.assertNotNull(dec5);
        Assertions.assertFalse(dec5.getActions().isEmpty());

        CeTianStrategy ct10 = new CeTianStrategy(10);
        Assertions.assertEquals(10, ct10.getSearchDepth());
        AiDecision dec10 = ct10.computeTurn(state, 2);
        Assertions.assertNotNull(dec10);
        Assertions.assertFalse(dec10.getActions().isEmpty());
    }

    @Test
    public void testJueYingStrategyDeepSearchAndWinningCut() {
        GameState state = new GameState(6);
        state.getBoard().lockEdge(0, 0, Direction.RIGHT, 1);
        state.getP2().setR(1);
        state.getP2().setC(0);
        state.getP2().setDirection(Direction.UP);
        state.setCurrentTurn(2);

        JueYingStrategy jy = (JueYingStrategy) AiPlaystyle.JUE_YING.createStrategy(6);
        Assertions.assertEquals(6, jy.getSearchDepth());

        AiDecision decision = jy.computeTurn(state, 2);
        Assertions.assertNotNull(decision);
        for (GameAction act : decision.getActions()) {
            GameEngine.executeAction(state, 2, act);
        }
        Assertions.assertTrue(state.isOver(), "绝影应当一击必杀斩断盘面");
        Assertions.assertEquals(2, state.getWinner(), "绝影应当获胜");
    }
}
